### PR TITLE
Client: introduce the retry func (honor 429 http code)

### PR DESCRIPTION
**Pull request by kayrus**
Introduces the common retry func for https://github.com/gophercloud/gophercloud/pull/2097 and https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1156

### CODE REVIEW

**Comment by kayrus** [comment]
@jtopjian ready for review

**Comment by kayrus** [comment]
Depends on https://github.com/gophercloud/gophercloud/pull/2106
I'd like to reuse the `RetryFunc` type pattern here as well.

**Comment by kayrus** [comment]
@jtopjian feel free to update gophercloud in go.mod after merging the https://github.com/gophercloud/gophercloud/pull/2106
and this PR also can be merged. Thanks in advance.

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
