### PR TITLE
Use user_domain_* instead of domain_*

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by jtopjian** [comment]
@mcanevet Thank you for pointing this out. Rather than replacing `DomainID` with `UserDomainID` (and `*Name`), `UserDomainID` and `UserDomainName` need to be added as additional fields. We then need to determine the correct `DomainID` and `DomainName` setting by following the precedence shown here:

https://github.com/openstack/os-client-config/blob/master/os_client_config/config.py#L593-L609

I've opened issue #4 to track this:

https://github.com/gophercloud/utils/issues/4

If you'd like to work on this, you're more than welcome to. Otherwise, I can take a look in the next day or two.

**Comment by mcanevet** [comment]
@jtopjian where would you put the code that determines the correct `DomainID` and `DomainName` to use?

**Comment by jtopjian** [comment]
It could go in the `AuthOptions` function here:

https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/requests.go#L104-L111

After re-reading the Python function again, I think it should be fine to add something like this:

```go
	if auth.UserDomainID != "" {
		ao.DomainID = auth.UserDomainID
	}

	if auth.UserDomainName != "" {
		ao.DomainName = auth.UserDomainName
	}
```

I think this might cause some scoping issues in certain situations, but I think that would need to be dealt with in Gophercloud (https://github.com/gophercloud/gophercloud/issues/252).

**Comment by mcanevet** [comment]
@jtopjian PR amended.

**Comment by jtopjian** [comment]
@mcanevet looks good, but the unit tests aren't passing (we need to get Travis hooked up to this repo).

The Domain settings need to be updated in the `testing/fixtures.go` file.

**Comment by mcanevet** [comment]
@jtopjian unit tests fixed

**Comment by jtopjian** [comment]
@mcanevet I think something might have gone awry with the last push. I see less code than before :)

**Comment by mcanevet** [comment]
@jtopjian I think it's normal, I removed the changes I did on unit tests because they are not required anymore with your suggestion to add fields and set the correct `DomainID` and `DomainName`.

**Pull request merged**
