### PR TITLE
Bump to gophercloud v2.0.0-beta.1 + CI Hygiene

### PR DESCRIPTION
**Pull request by EmilienM**
Bump Gophercloud to v2.0.0-beta.1

### CODE REVIEW

**Comment by pierreprinetti** [comment]
What do you think about changing the module name in go.mod to `github.com/gophercloud/utils/v2`? So that the two versions are independently usable

**Comment by EmilienM** [comment]
ping @gophercloud/core

**Review by mandre — COMMENTED** [review]
Why do we start vendoring?

**Review by mandre — COMMENTED** [review]
Also, rather than deleting the acceptance tests, shouldn't we try to setup jobs like we did for the gophercloud repo?

**Comment by EmilienM** [comment]
I removed vendoring, but I won't do acceptance, really not worth it IMO.

**Review by mandre — APPROVED** [review]
We need a v2 of utils for people to consume gophercloud v2. Let's not block for the deleted acceptance tests.

LGTM.

**Pull request merged**
