### PR TITLE
[terraform]: allow to override service type

### LINKED ISSUE #228: terraform: add an ability to override endpoint service name
Currently there is an ability to override endpoint URL to a static URL. However there is a case to override the endpoint service type to an alias, e.g. replace `object-store` with the `object-store-beta`. This change also must not depend on the original service type, e.g. if the catalog doesn't contain the `object-store`, we still need to replace it with the `object-store-beta` if possible.

There could be 3 scenarios:

There is no `object-store` service in the catalog, but there is `object-store-beta` service and we want to use it:

```
endpoint_overrides = {
  "object-store" = "object-store-beta"
}
```

There is `object-store` service in the catalog, but there is also `object-store-beta` service and we want to use it instead:

```
endpoint_overrides = {
  "object-store" = "object-store-beta"
}
```

There is neither `object-store` nor `object-store-beta` in the catalog, but we just want to override the service URL:

```
endpoint_overrides = {
  "object-store" = "http://localhost/v1/AUTH_679d134152e248118a3c34c4d4900add/"
}
```

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #228

### CODE REVIEW

**Comment by kayrus** [comment]
@pierreprinetti @mandre @EmilienM kindly ping

**Review by pierreprinetti — APPROVED** [review]
Why do we even have a Terraform directory in utils? What is its purpose?

I have nothing against merging this, but I think we should have a migration plan for moving this code to the Terraform provider, if it's needed there

**Comment by kayrus** [comment]
> Why do we even have a Terraform directory in utils? What is its purpose?

initially this was in the openstack terraform project, but this code is used in other terraform related projects that use non-vanilla openstack services. at some point we decided to move it into the gophercloud/utils to reduce the dependency tree.

**Comment by pierreprinetti** [comment]
Do you think that having all Gophercloud functions accept ServiceClient as an interface ([as proposed here](https://github.com/gophercloud/gophercloud/pull/3203)) would solve this use-case?

**Comment by kayrus** [comment]
In theory yes, but the code base should contain some extra logic. Anyway, I don't think that terraform helper code will be rewritten after introducing the client interface.

**Comment by pierreprinetti** [comment]
>I don't think that terraform helper code will be rewritten after introducing the client interface

Indeed, that's fair. I'll keep my spring-cleaning instincts under control for the time being

**Pull request merged**
