### PR TITLE
clientconfig: add RegionName to ClientOpts

### PR DESCRIPTION
**Pull request by jtopjian**
For #48

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
I prefer if `opts` has the highest priority.

**Comment by jtopjian** [comment]
You mean over environment variables? Environment variables always have the final say.

**Comment by rickard-von-essen** [comment]
I'm working on Packer, I see you have worked on the OpenStack Terraform provider. In both of them application configuration overrides `cloud.yaml` and environment variables.

**Comment by jtopjian** [comment]
> In both of them application configuration overrides cloud.yaml and environment variables.

Unless the application and the application's environment variables are configured to match this `clientconfig` package. 

If Packer is using different environment variables which would conflict with `NewServiceClient`, then I would say `NewServiceClient` isn't suitable for Packer and a custom `NewServiceClient`-ish function local to Packer might be better.

Even though Terraform's environment variables match this package's environment variables, it still does not use `NewServiceClient` as there are too many other finer details it needs to account for. All of Terraform's [`config.go`](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/config.go) file can be thought of as one Terraform-specific `NewServiceClient` function.

**Comment by rickard-von-essen** [comment]
Ok, I thought this was a generalisation of Terraforms `config.go`. But if it's not I think I'll just copy over Terraforms over to Packer and m.m.

**Comment by jtopjian** [comment]
Ah, understood.

This `clientconfig` package as a whole is an attempt to mirror OpenStack's `os-client-config` library, which provides various convenience features and functions to authenticate. There are a bunch of functions within `clientconfig` which can be used together or individually, depending on what works best for the situation at hand. 

It's always possible that certain situations won't be able to use anything in `clientconfig`. In that case, the app developer would have to fall back to `gophercloud/gophercloud` directly.

Terraform does not use the `NewServiceClient` function, but uses `clientconfig` in two places: https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/config.go#L73-L106

It then goes on to configure the rest of the Terraform session in further detail.

Terraform creates a hard separation between someone using a `clouds.yaml` file and someone authenticating with options explicitly set in Terraform. A combination of the two doesn't happen since, as you've raised, precedence becomes very difficult.

On the topic of regions specifically, Terraform handles this in a very unique way. It's possible to set a region at the provider-level and within _each_ resource. 

If you have any questions about what Terraform's doing, please let me know. It's an accumulation of 4 years of work, so there's a lot of functionality accounted for.

But coming back to this PR: I think your request to have `RegionName` within `NewServiceClient` is still very valid. I think `NewServiceClient` will work for 80% of the applications written with Gophercloud. Larger applications, such as Terraform and Packer, will have unique needs outside of it, though.

**Pull request merged**
